# Numpy

Unlike Matlab or R, Python is a general purpose programming language that was not designed for scientific computing or data analysis. For this purpose, we have to use the well known NumPy (Numerical Python) package. 

In [3]:
import numpy as np

def printbl(*args):
    print(*args, '\n')

## References

* Python for Data Analysis, Chapter 4, by Wes McKinney, O'REILLY
* [NumPy Reference](http://docs.scipy.org/doc/numpy-dev/reference/index.html)

## Multidimensional Array : ndarray

Execute and explain (with comments) what follows. Compare the following thow cells. What do you conclude from this ?

In [4]:
data1 = [6, 7.5, 8, 0, 1] 
print(type(data1))
print(type(data1[0]))
print(type(data1[1]))

<class 'list'>
<class 'int'>
<class 'float'>


In [5]:
data2 = np.array([6, 7.5, 8, 0, 1])
print(type(data2))
print(type(data2[0]))
print(type(data2[1]))

<class 'numpy.ndarray'>
<class 'numpy.float64'>
<class 'numpy.float64'>


Compare the following thow cells. What do you conclude from this ?

In [6]:
data1 * 2

[6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1]

In [7]:
data2 * 2

array([ 12.,  15.,  16.,   0.,   2.])

What is the number of dimensions of the `ndarray` referred by `data4`?

In [8]:
data3 = [[1, 2, 3], [4, 5]]
data4 = np.array([[1, 2, 3], [4, 5]])
print(data4)
print(data4.shape)
print(type(data4[0]))
print(data4*10)

[[1, 2, 3] [4, 5]]
(2,)
<class 'list'>
[ [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
 [4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5]]


What is the number of dimensions of the `ndarray` referred by `data5`?

In [9]:
data5 = np.array([[1, 2, 3], [4, 5, 6]])
print(data5)
print(data5.shape)
print(type(data5[0]))
print(data5*10)


[[1 2 3]
 [4 5 6]]
(2, 3)
<class 'numpy.ndarray'>
[[10 20 30]
 [40 50 60]]


What is the shape of the following `ndarray` ?

In [10]:
data6 = np.array([[1, 2, 3], [4, 5, 6], [4, 5, 6], [4, 5, 6]])
print(data6.ndim)

2


### Indexing

In [11]:
x = np.arange(10)
print(id(x))
x[2:7] = 8.6
print(x)
print(id(x))

140170017398576
[0 1 8 8 8 8 8 7 8 9]
140170017398576


In [12]:
x = np.arange(10, dtype=np.float64)
x[2:7] = 8.6
print(x)
x[:] = 1.2
print(x)

[ 0.   1.   8.6  8.6  8.6  8.6  8.6  7.   8.   9. ]
[ 1.2  1.2  1.2  1.2  1.2  1.2  1.2  1.2  1.2  1.2]


In [13]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[0][2])
print(arr2d[0, 2])

3
3


In [14]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
old_values = arr2d[0].copy()
arr2d[0] = 42
arr2d[0] = old_values
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
old_values = arr2d[0]
arr2d[0] = 42
arr2d[0] = old_values
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[42 42 42]
 [ 4  5  6]
 [ 7  8  9]]


In [16]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
arr2d[:, 2] = 7
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 7]
 [4 5 7]
 [7 8 7]]


### Boolean Indexing

In [17]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(data)
print(names == 'Bob')
print(data[names == 'Bob'])
print(data[(names == 'Bob') | (names == 'Will')])

[[ 2.13995793  0.64098028 -0.38425839  0.47307753]
 [ 0.83363509 -0.2253946   0.68461507 -0.09032787]
 [-1.46337586 -0.25373862 -0.1933356  -0.4557746 ]
 [-0.26739707 -1.47420883  0.58219502  0.12256404]
 [ 0.88306807 -1.84701421 -1.20779229  2.1748726 ]
 [-1.54435312 -1.78176044  1.62107529  0.10021914]
 [ 1.87339652  0.05707006  0.59717053 -0.89781827]]
[ True False False  True False False False]
[[ 2.13995793  0.64098028 -0.38425839  0.47307753]
 [-0.26739707 -1.47420883  0.58219502  0.12256404]]
[[ 2.13995793  0.64098028 -0.38425839  0.47307753]
 [-1.46337586 -0.25373862 -0.1933356  -0.4557746 ]
 [-0.26739707 -1.47420883  0.58219502  0.12256404]
 [ 0.88306807 -1.84701421 -1.20779229  2.1748726 ]]


In [18]:
data = np.random.randn(7, 4)
print(data)
data[data < 0] = 0
print(data)

[[ 0.72150197 -0.05426622  0.39527034 -3.04405579]
 [ 0.67537031 -0.37201629  0.56654202 -0.54725008]
 [ 0.15292982 -0.35257556  0.95466414  0.51294492]
 [ 0.8266292  -0.66835738  1.06710919 -0.03098061]
 [ 0.26203564  0.09570646  1.81320354 -2.69421281]
 [-2.197255   -0.49910637  0.02773755 -0.10141492]
 [-0.98152018 -0.76230036  1.03505704  0.6943345 ]]
[[ 0.72150197  0.          0.39527034  0.        ]
 [ 0.67537031  0.          0.56654202  0.        ]
 [ 0.15292982  0.          0.95466414  0.51294492]
 [ 0.8266292   0.          1.06710919  0.        ]
 [ 0.26203564  0.09570646  1.81320354  0.        ]
 [ 0.          0.          0.02773755  0.        ]
 [ 0.          0.          1.03505704  0.6943345 ]]


### Transposing

In [19]:
X = np.arange(15).reshape((3, 5))
printbl(X)
print(X.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


### Swapping Axes

In [20]:
X = np.arange(30).reshape((3, 10))
print(X)
np.swapaxes(X, 0, 1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


array([[ 0, 10, 20],
       [ 1, 11, 21],
       [ 2, 12, 22],
       [ 3, 13, 23],
       [ 4, 14, 24],
       [ 5, 15, 25],
       [ 6, 16, 26],
       [ 7, 17, 27],
       [ 8, 18, 28],
       [ 9, 19, 29]])

In [21]:
X = np.arange(30).reshape((3, 2, 5))
printbl(X[:,1,1])
print(X[1,1,:])
np.swapaxes(X, 0, 2)[:,1,1]

[ 6 16 26] 

[15 16 17 18 19]


array([15, 16, 17, 18, 19])

### Numerical operations (Elementwise)

In [22]:
X = np.zeros((3,6))
print(X)

print()

X = X + 3
print(X)

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]

[[ 3.  3.  3.  3.  3.  3.]
 [ 3.  3.  3.  3.  3.  3.]
 [ 3.  3.  3.  3.  3.  3.]]


In [23]:
Y = np.ones((3,6))
X - Y

array([[ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.]])

In [24]:
x = np.array([1, 2, 3, 1.5])
x * 2

array([ 2.,  4.,  6.,  3.])

Let us compare the performance of these operations with Numpy and standard Python constructs :

In [25]:
nparray = np.arange(100)
%timeit nparray * 2

pylist = range(100)
%timeit [x * 2 for x in pylist]

np.array_equal(nparray * 2, np.array([x * 2 for x in pylist]))

The slowest run took 29.47 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 925 ns per loop
100000 loops, best of 3: 6.01 µs per loop


True

In [26]:
print(np.ones((3,3)) - np.identity(3))

[[ 0.  1.  1.]
 [ 1.  0.  1.]
 [ 1.  1.  0.]]


In [27]:
empty_array = np.empty(8, dtype=np.float64)

In [28]:
x = np.arange(10)
x **= 2
print(id(x))
print(x)
x = x ** 2
print(id(x))
print(x)

140170017437696
[ 0  1  4  9 16 25 36 49 64 81]
140170017437776
[   0    1   16   81  256  625 1296 2401 4096 6561]


In [29]:
X = np.arange(15).reshape((3, 5))
printbl(X, )
printbl(X * X) # Not matrix multiplication
printbl(np.dot(X, X.T))
printbl(np.sqrt(X))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]] 

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]] 

[[ 0.          1.          1.41421356  1.73205081  2.        ]
 [ 2.23606798  2.44948974  2.64575131  2.82842712  3.        ]
 [ 3.16227766  3.31662479  3.46410162  3.60555128  3.74165739]] 



## Reductions

Operations considered in this sections are known as reduction. In other words, these operations produce a single value from a 1D array.

In [30]:
x = np.array([3, 6, 2, 4])
np.sum(x)

15

In [31]:
x = np.array([3, 6, 2, 4])
x.sum()

15

In [32]:
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
printbl(X)
printbl("Reduction applied on the flattened array :", np.sum(X))
printbl("Reduction applied on columns (first dimension) :", np.sum(X, axis=0))
printbl("Reduction applied on rows (second dimension) :", np.sum(X, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Reduction applied on the flattened array : 45 

Reduction applied on columns (first dimension) : [12 15 18] 

Reduction applied on rows (second dimension) : [ 6 15 24] 



In [33]:
x = np.random.randn(100)
printbl(x > 0)
print((x > 0).sum())

[False  True False  True False False  True False  True  True False  True
 False  True  True  True False  True False  True  True  True False  True
  True False  True False  True False False  True  True False False  True
 False False  True  True  True  True  True False  True  True  True  True
 False False False  True False  True False  True  True  True False False
  True False False  True False False False False  True False  True  True
  True  True  True False False False  True False False False  True False
 False  True  True  True False  True False  True False False False False
  True False  True False] 

51


In [34]:
x = np.random.randn(100)
print((x > 0).any())
print((x > 0).all())
print(np.all(x > 0))

True
False
False


### Sorting and Searching (see [here](http://docs.scipy.org/doc/numpy/reference/routines.sort.html))

In [35]:
x = np.random.randn(1000)
print(np.sort(x)[-1])
print(np.max(x))

3.23111332359
3.23111332359


In [37]:
x = np.random.randn(4, 4)
printbl(x)
np.where(x > 0, 2, -2)

[[-1.67179289 -0.42303667 -0.11649064  0.00899382]
 [ 0.20753813 -0.91188838 -1.84927231 -1.75064008]
 [-0.43366726  0.2594172  -0.97188587  1.2779212 ]
 [-1.00046396  1.75590491 -0.64423651  1.56043493]] 



array([[-2, -2, -2,  2],
       [ 2, -2, -2, -2],
       [-2,  2, -2,  2],
       [-2,  2, -2,  2]])

In [38]:
x = np.random.randn(4, 4)
printbl(x)
np.where(x < 0, 0, x)

[[ 0.63004782  0.81992702 -1.36257462  1.18731634]
 [-0.09587903 -3.5245056   0.20737558  0.24446436]
 [ 0.29482423  0.18538542 -1.00233878 -0.91695032]
 [ 0.07186758 -1.72589919 -1.16626341 -0.61493405]] 



array([[ 0.63004782,  0.81992702,  0.        ,  1.18731634],
       [ 0.        ,  0.        ,  0.20737558,  0.24446436],
       [ 0.29482423,  0.18538542,  0.        ,  0.        ],
       [ 0.07186758,  0.        ,  0.        ,  0.        ]])

In [39]:
X = np.random.randn(2,5) * 0.1 + 10
printbl(X)
printbl(np.argmin(X)) # returns the index in the flattened array
printbl(np.argmin(X, axis=0)) # indices with respect to the first axis
printbl(np.argmin(X, axis=1)) # indices with respect to the second axis

[[  9.94944134   9.92349224   9.92214553  10.08975022   9.96569121]
 [  9.89177589   9.91495412  10.16007127  10.18374294   9.87387151]] 

9 

[1 1 0 0 1] 

[2 4] 



## Exercises

##### Compare the performance of the sum of  elements of `np.arange(1000)` (with the `sum()` mathematical function) and `range(1000)` (with a standard python for loop).

In [ ]:
a = np.arange(1000)
l = range(1000)

##### Without the use of control flow statements, replace all the values of the following matrix that are not in the intervale $[\mu - \sigma, \mu + \sigma]$ by zero (see, [statistics](http://docs.scipy.org/doc/numpy/reference/routines.statistics.html)). 

In [ ]:
X = np.random.randn(5, 4)

##### Write a function to compute the median of the following two arrays without the use of [numpy.median](http://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.median.html). Compare your result with the value returned by numpy.median.

In [ ]:
x = np.random.randn(1001)
y = np.random.randn(1000)

##### Without the use of control flow statements, determine the indices along the two axis of the first maximal element in the following matrix. 

In [ ]:
X = np.random.randn(5, 8)

##### Without the use of control flow statements, compute the mean of each variable from the following data matrix (D) (see, [numpy.mean](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html#numpy.mean)).

In [ ]:
D = np.random.randn(5, 4)

print(D)

for i in range(4):
    data_i = D[:,i]
    print("Data from variable {} : {} (mean : {})".format(i, data_i, np.mean(data_i)))

###### What is the difference between np.random.randn() and np.random.rand() ?

###### Use routines from numpy.linalg (see [Linear algebra](http://docs.scipy.org/doc/numpy/reference/routines.linalg.html)) to solve the following system of equations (from [System of linear equations ](https://en.wikipedia.org/wiki/System_of_linear_equations)) :  $$ \begin{alignat}{7} 3x &&\; + \;&& 2y             &&\; - \;&& z  &&\; = \;&& 1 & \\ 2x &&\; - \;&& 2y             &&\; + \;&& 4z &&\; = \;&& -2 & \\ -x &&\; + \;&& \tfrac{1}{2} y &&\; - \;&& z  &&\; = \;&& 0 & \end{alignat} $$

###### Complete the following code by using routines from numpy.linalg to determine a line of equation $y = mx + p$ that fits the given data points.

In [ ]:
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

x = np.arange(-0.5, 0.5, 0.01)
y = (2 * x + 3) + np.random.randn(100) * 0.1

plt.plot(x, y, 'o', label='Original data', markersize=5)
    